import type {
  ActionCenterModel,
  ActionItem,
  CalendarEvent,
  Family,
  FamilyActionStatus,
  FamilyProgressSummary,
  Huddle,
  HuddleHomeModel,
  HuddleSection,
  Team,
  VolunteerCenterModel,
  VolunteerSlot,
  VolunteerSlotWithSignupSummary,
} from '@gridiron/shared'

const now = '2026-05-18T09:00:00-07:00'

export const demoTeams: Team[] = [
  {
    id: '10000000-0000-0000-0000-000000000001',
    name: 'All Program',
    level: 'all_program',
    sport: 'football',
    season: '2026',
    school_name: 'Woodinville High School',
    created_at: now,
  },
  {
    id: '10000000-0000-0000-0000-000000000002',
    name: 'Varsity',
    level: 'varsity',
    sport: 'football',
    season: '2026',
    school_name: 'Woodinville High School',
    created_at: now,
  },
]

export const demoFamily: Family = {
  id: '80000000-0000-0000-0000-000000000001',
  name: 'Bergerin Family',
  primary_contact_id: null,
  notes: null,
  created_at: now,
  updated_at: now,
}

export const currentHuddle: Huddle = {
  id: '30000000-0000-0000-0000-000000000001',
  title: '2026 Key Dates',
  date_range: 'January 5-September 7, 2026',
  starts_on: '2026-01-05',
  ends_on: '2026-09-07',
  summary: 'Key dates and upcoming events are kept current on the website under the Parents tab.',
  status: 'published',
  target_team_id: demoTeams[0].id,
  created_by: null,
  published_by: null,
  published_at: '2026-01-05T00:00:00+00:00',
  created_at: now,
  updated_at: now,
}

export const currentHuddleSections: HuddleSection[] = [
  {
    id: '31000000-0000-0000-0000-000000000001',
    huddle_id: currentHuddle.id,
    section_type: 'urgent',
    title: 'CWU Camp Registration Deadline',
    body: 'June 3rd Registration Deadline',
    sort_order: 1,
    metadata: { badge: 'June 3' },
    created_at: now,
  },
  {
    id: '31000000-0000-0000-0000-000000000002',
    huddle_id: currentHuddle.id,
    section_type: 'actions',
    title: 'Complete all 3 registration steps below',
    body: 'Register Online with CWU. Pay Camp Fee to Woodinville High School. Submit Hard Copies of Forms.',
    sort_order: 2,
    metadata: {},
    created_at: now,
  },
  {
    id: '31000000-0000-0000-0000-000000000003',
    huddle_id: currentHuddle.id,
    section_type: 'calendar',
    title: '2026 Key Dates',
    body: 'Key dates and upcoming events are kept current on the website under the Parents tab.',
    sort_order: 3,
    metadata: {},
    created_at: now,
  },
  {
    id: '31000000-0000-0000-0000-000000000004',
    huddle_id: currentHuddle.id,
    section_type: 'highlights',
    title: '2019 4A Academic State Champions (Football)',
    body: '3-PEAT 4A STATE SEMI-FINALISTS',
    sort_order: 4,
    metadata: {
      highlights: [
        '2019 4A Academic State Champions (Football)',
        '3-PEAT 4A STATE SEMI-FINALISTS',
        '3-PEAT KINGCO 4A CHAMPIONS',
      ],
    },
    created_at: now,
  },
]

export const demoActionItems: ActionItem[] = [
  {
    id: '40000000-0000-0000-0000-000000000001',
    huddle_id: currentHuddle.id,
    title: 'FinalForms Registration',
    description: 'In order to participate in the first day of summer conditioning/practice, tryouts or regular season practice, a FinalForms registration must be completed by both parent and student and a current sports physical must be on file with the WHS Athletic Office.',
    importance: 'required',
    default_status: 'not_started',
    due_at: '2026-05-26T23:59:00-07:00',
    due_label: 'Due May 26',
    audience_label: 'All players',
    target_team_id: demoTeams[0].id,
    external_url: 'https://woodinville.nsd.org/athletics/register-for-athletics',
    created_by: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: '40000000-0000-0000-0000-000000000002',
    huddle_id: currentHuddle.id,
    title: 'CWU Camp Registration',
    description: 'Complete all 3 registration steps below.',
    importance: 'required',
    default_status: 'not_started',
    due_at: '2026-06-03T23:59:00-07:00',
    due_label: 'Due June 3',
    audience_label: 'Camp attendees',
    target_team_id: demoTeams[0].id,
    external_url: 'https://www.woodinvillefootball.com/cwucamp',
    created_by: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: '40000000-0000-0000-0000-000000000003',
    huddle_id: currentHuddle.id,
    title: '2026 FGIC Membership',
    description: '$500/Family FGIC Membership dues help support the many resources that make the Woodinville High School Football program successful.',
    importance: 'family',
    default_status: 'not_started',
    due_at: null,
    due_label: 'Past due',
    audience_label: 'All families',
    target_team_id: demoTeams[0].id,
    external_url: 'https://www.woodinvillefootball.com/dues',
    created_by: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: '40000000-0000-0000-0000-000000000004',
    huddle_id: currentHuddle.id,
    title: '2026 Key Dates',
    description: 'Key dates and upcoming events are kept current on the website under the Parents tab.',
    importance: 'info',
    default_status: 'not_started',
    due_at: null,
    due_label: null,
    audience_label: 'All families',
    target_team_id: demoTeams[0].id,
    external_url: 'https://www.woodinvillefootball.com/keydates',
    created_by: null,
    created_at: now,
    updated_at: now,
  },
]

export const demoFamilyActionStatuses: FamilyActionStatus[] = demoActionItems.map((action) => ({
  id: `90000000-0000-0000-0000-${action.id.slice(-12)}`,
  family_id: demoFamily.id,
  action_item_id: action.id,
  status: action.default_status,
  completed_by: null,
  completed_at: null,
  admin_note: null,
  created_at: now,
  updated_at: now,
}))

export const demoEvents: CalendarEvent[] = [
  {
    id: '50000000-0000-0000-0000-000000000001',
    title: 'CWU Camp Registration Deadline',
    event_type: 'deadline',
    team_id: demoTeams[0].id,
    audience_label: 'Camp attendees',
    starts_at: '2026-06-03T23:59:00-07:00',
    ends_at: null,
    display_date: 'Jun 3',
    display_time: '11:59 PM',
    location: 'Central Washington University',
    address: null,
    arrival_time: null,
    bus_time: null,
    uniform_note: null,
    equipment_note: null,
    notes: 'Registration Deadline: June 3',
    external_url: 'https://www.woodinvillefootball.com/cwucamp',
    is_canceled: false,
    created_by: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: '50000000-0000-0000-0000-000000000002',
    title: 'Spring Practices',
    event_type: 'practice',
    team_id: demoTeams[0].id,
    audience_label: 'All teams',
    starts_at: '2026-06-01T15:00:00-07:00',
    ends_at: '2026-06-18T18:00:00-07:00',
    display_date: 'Jun 1',
    display_time: 'June 1-18',
    location: null,
    address: null,
    arrival_time: null,
    bus_time: null,
    uniform_note: null,
    equipment_note: null,
    notes: 'More Details Coming',
    external_url: 'https://www.woodinvillefootball.com/keydates',
    is_canceled: false,
    created_by: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: '50000000-0000-0000-0000-000000000003',
    title: 'Travel trip to Hawaii',
    event_type: 'travel',
    team_id: demoTeams[0].id,
    audience_label: 'Seniors, Juniors & Sophomores',
    starts_at: '2026-09-03T00:00:00-07:00',
    ends_at: '2026-09-07T23:59:00-07:00',
    display_date: 'Sep 3',
    display_time: 'September 3-7',
    location: null,
    address: null,
    arrival_time: null,
    bus_time: null,
    uniform_note: null,
    equipment_note: null,
    notes: 'Travel trip to Hawaii : September 3rd-7th - Seniors, Juniors & Sophomores',
    external_url: 'https://www.woodinvillefootball.com/keydates',
    is_canceled: false,
    created_by: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: '50000000-0000-0000-0000-000000000004',
    title: 'Mini Camp',
    event_type: 'practice',
    team_id: demoTeams[0].id,
    audience_label: 'All program',
    starts_at: '2026-07-21T00:00:00-07:00',
    ends_at: '2026-07-23T23:59:00-07:00',
    display_date: 'Jul 21',
    display_time: 'July 21-23',
    location: 'WHS Football Field',
    address: null,
    arrival_time: null,
    bus_time: null,
    uniform_note: null,
    equipment_note: null,
    notes: 'Mini Camp : July 21st - 23rd @ WHS Football Field',
    external_url: 'https://www.woodinvillefootball.com/keydates',
    is_canceled: false,
    created_by: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: '50000000-0000-0000-0000-000000000005',
    title: 'Start of WIAA Season',
    event_type: 'other',
    team_id: demoTeams[0].id,
    audience_label: 'All program',
    starts_at: '2026-08-19T00:00:00-07:00',
    ends_at: null,
    display_date: 'Aug 19',
    display_time: null,
    location: null,
    address: null,
    arrival_time: null,
    bus_time: null,
    uniform_note: null,
    equipment_note: null,
    notes: 'Start of WIAA Season : August 19th',
    external_url: 'https://www.woodinvillefootball.com/keydates',
    is_canceled: false,
    created_by: null,
    created_at: now,
    updated_at: now,
  },
]

export const demoVolunteerSlots: VolunteerSlot[] = [
  {
    id: '60000000-0000-0000-0000-000000000001',
    title: 'Director of Game Day Operations',
    description: 'Open',
    category: 'game_day',
    team_id: demoTeams[0].id,
    event_id: null,
    starts_at: null,
    ends_at: null,
    display_date: 'Open',
    display_time: null,
    location: null,
    slots_needed: 1,
    hour_credit: 0,
    coordinator_profile_id: null,
    created_by: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: '60000000-0000-0000-0000-000000000002',
    title: 'Team Dinners',
    description: 'Team Dinners happen the night before a Varsity game.',
    category: 'meals',
    team_id: demoTeams[0].id,
    event_id: null,
    starts_at: null,
    ends_at: null,
    display_date: 'Night before a Varsity game',
    display_time: null,
    location: null,
    slots_needed: 1,
    hour_credit: 0,
    coordinator_profile_id: null,
    created_by: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: '60000000-0000-0000-0000-000000000003',
    title: 'Friday Night Lights',
    description: 'A community scrimmage event (usually the Friday before school) where the Woodinville team plays, junior football pairs with high school buddies, cheer leads the crowd — a fun kickoff night for the season.',
    category: 'events',
    team_id: demoTeams[0].id,
    event_id: null,
    starts_at: null,
    ends_at: null,
    display_date: 'Usually the Friday before school',
    display_time: null,
    location: null,
    slots_needed: 1,
    hour_credit: 0,
    coordinator_profile_id: null,
    created_by: null,
    created_at: now,
    updated_at: now,
  },
]

export const demoVolunteerSlotsWithSummary: VolunteerSlotWithSignupSummary[] = demoVolunteerSlots.map((slot) => ({
  ...slot,
  slots_filled: 0,
  signed_up_family_ids: [],
}))

export const demoFamilyProgress: FamilyProgressSummary = {
  action_items_complete: 0,
  action_items_total: 4,
  volunteer_hours_complete: 0,
  volunteer_hours_goal: 10,
}

export const huddleHomeDemo: HuddleHomeModel = {
  huddle: currentHuddle,
  sections: currentHuddleSections,
  urgent_actions: demoActionItems.filter((action) => action.title !== '2026 Key Dates'),
  due_soon_actions: demoActionItems.filter((action) => action.due_at).slice(0, 3),
  upcoming_events: demoEvents,
  volunteer_needs: demoVolunteerSlots,
  family_progress: demoFamilyProgress,
}

export const actionCenterDemo: ActionCenterModel = {
  family: demoFamily,
  items: demoActionItems.map((action) => ({
    action,
    status: demoFamilyActionStatuses.find((status) => status.action_item_id === action.id)!,
  })),
  progress: demoFamilyProgress,
}

export const volunteerCenterDemo: VolunteerCenterModel = {
  slots: demoVolunteerSlotsWithSummary,
  claimed_shifts: [],
  volunteer_hours_complete: demoFamilyProgress.volunteer_hours_complete,
  volunteer_hours_goal: demoFamilyProgress.volunteer_hours_goal,
}
