import type {
  ActionCenterModel,
  ActionItem,
  CalendarEvent,
  Family,
  FamilyActionStatus,
  FamilyProgressSummary,
  Huddle,
  HuddleHomeModel,
  HuddleSection,
  Team,
  VolunteerCenterModel,
  VolunteerSlot,
  VolunteerSlotWithSignupSummary,
} from '@gridiron/shared'

const now = '2026-05-18T09:00:00-07:00'

export const demoTeams: Team[] = [
  {
    id: '10000000-0000-0000-0000-000000000001',
    name: 'All Program',
    level: 'all_program',
    sport: 'football',
    season: '2026',
    school_name: 'Woodinville High School',
    created_at: now,
  },
  {
    id: '10000000-0000-0000-0000-000000000002',
    name: 'Varsity',
    level: 'varsity',
    sport: 'football',
    season: '2026',
    school_name: 'Woodinville High School',
    created_at: now,
  },
]

export const demoFamily: Family = {
  id: '80000000-0000-0000-0000-000000000001',
  name: 'Sabol family',
  primary_contact_id: '20000000-0000-0000-0000-000000000002',
  notes: null,
  created_at: now,
  updated_at: now,
}

export const currentHuddle: Huddle = {
  id: '30000000-0000-0000-0000-000000000001',
  title: 'Weekly Huddle',
  date_range: 'May 17-24, 2026',
  starts_on: '2026-05-17',
  ends_on: '2026-05-24',
  summary: "This week's playbook for registration, camp, dues, calendar updates, and program highlights.",
  status: 'published',
  target_team_id: demoTeams[0].id,
  created_by: null,
  published_by: null,
  published_at: '2026-05-17T17:12:00+00:00',
  created_at: now,
  updated_at: now,
}

export const currentHuddleSections: HuddleSection[] = [
  {
    id: '31000000-0000-0000-0000-000000000001',
    huddle_id: currentHuddle.id,
    section_type: 'urgent',
    title: 'Urgent: FinalForms Registration',
    body: 'Athletes must complete online forms before gear checkout, Spring Football, and CWU Camp.',
    sort_order: 1,
    metadata: { badge: 'Due May 26' },
    created_at: now,
  },
  {
    id: '31000000-0000-0000-0000-000000000002',
    huddle_id: currentHuddle.id,
    section_type: 'actions',
    title: "This Week's Playbook",
    body: 'Required family action items and deadlines.',
    sort_order: 2,
    metadata: {},
    created_at: now,
  },
  {
    id: '31000000-0000-0000-0000-000000000003',
    huddle_id: currentHuddle.id,
    section_type: 'highlights',
    title: 'Program Highlights',
    body: 'Gervais training turnout has been strong this offseason. Congratulations to Woodinville Baseball and Jonah Leavengood.',
    sort_order: 3,
    metadata: {
      highlights: [
        'Gervais training turnout has been strong this offseason.',
        'Woodinville Baseball won KingCo and District championships.',
        'Jonah Leavengood won the KingCo 400 meter title for Woodinville Track.',
      ],
    },
    created_at: now,
  },
]

export const demoActionItems: ActionItem[] = [
  {
    id: '40000000-0000-0000-0000-000000000001',
    huddle_id: currentHuddle.id,
    title: 'FinalForms Registration',
    description: 'Complete Northshore School District athletics forms and select both Summer Football and Fall Football.',
    importance: 'required',
    default_status: 'not_started',
    due_at: '2026-05-26T23:59:00-07:00',
    due_label: 'Due May 26',
    audience_label: 'All players',
    target_team_id: demoTeams[0].id,
    external_url: 'https://woodinville.nsd.org/athletics/register-for-athletics',
    created_by: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: '40000000-0000-0000-0000-000000000002',
    huddle_id: currentHuddle.id,
    title: 'CWU Camp Registration',
    description: 'Follow the three-step registration process on the Woodinville Football CWU Camp page.',
    importance: 'required',
    default_status: 'in_progress',
    due_at: '2026-06-03T23:59:00-07:00',
    due_label: 'Due June 3',
    audience_label: 'Camp attendees',
    target_team_id: demoTeams[0].id,
    external_url: 'https://www.woodinvillefootball.com/cwucamp',
    created_by: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: '40000000-0000-0000-0000-000000000003',
    huddle_id: currentHuddle.id,
    title: 'FGIC Membership',
    description: 'Membership dues help fund the player experience on and off the field.',
    importance: 'family',
    default_status: 'not_started',
    due_at: null,
    due_label: 'Past due',
    audience_label: 'All families',
    target_team_id: demoTeams[0].id,
    external_url: 'https://www.woodinvillefootball.com/dues',
    created_by: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: '40000000-0000-0000-0000-000000000004',
    huddle_id: currentHuddle.id,
    title: 'Review coach calendar',
    description: 'Review the digital coach calendar regularly. Avoid printing it as a final schedule.',
    importance: 'optional',
    default_status: 'not_started',
    due_at: null,
    due_label: 'This week',
    audience_label: 'All families',
    target_team_id: demoTeams[0].id,
    external_url: 'https://www.woodinvillefootball.com/calendar',
    created_by: null,
    created_at: now,
    updated_at: now,
  },
]

export const demoFamilyActionStatuses: FamilyActionStatus[] = demoActionItems.map((action) => ({
  id: `90000000-0000-0000-0000-${action.id.slice(-12)}`,
  family_id: demoFamily.id,
  action_item_id: action.id,
  status: action.title === 'Review coach calendar' ? 'complete' : action.default_status,
  completed_by: action.title === 'Review coach calendar' ? demoFamily.primary_contact_id : null,
  completed_at: action.title === 'Review coach calendar' ? now : null,
  admin_note: null,
  created_at: now,
  updated_at: now,
}))

export const demoEvents: CalendarEvent[] = [
  {
    id: '50000000-0000-0000-0000-000000000001',
    title: 'Spring eligibility deadline',
    event_type: 'deadline',
    team_id: demoTeams[0].id,
    audience_label: 'All program',
    starts_at: '2026-05-26T23:59:00-07:00',
    ends_at: null,
    display_date: 'May 26',
    display_time: '11:59 PM',
    location: 'FinalForms',
    address: null,
    arrival_time: null,
    bus_time: null,
    uniform_note: null,
    equipment_note: null,
    notes: 'Athletes must complete FinalForms before gear checkout and Spring Football.',
    external_url: 'https://woodinville.nsd.org/athletics/register-for-athletics',
    is_canceled: false,
    created_by: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: '50000000-0000-0000-0000-000000000002',
    title: 'Spring Football begins',
    event_type: 'practice',
    team_id: demoTeams[0].id,
    audience_label: 'All teams',
    starts_at: '2026-06-01T15:00:00-07:00',
    ends_at: null,
    display_date: 'Jun 1',
    display_time: 'After school',
    location: 'Woodinville High School',
    address: null,
    arrival_time: null,
    bus_time: null,
    uniform_note: null,
    equipment_note: 'Practice gear',
    notes: 'Times will follow the coach calendar. Check the digital calendar for updates.',
    external_url: 'https://www.woodinvillefootball.com/calendar',
    is_canceled: false,
    created_by: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: '50000000-0000-0000-0000-000000000004',
    title: 'CWU Camp',
    event_type: 'camp',
    team_id: demoTeams[0].id,
    audience_label: 'Camp attendees',
    starts_at: '2026-06-20T08:00:00-07:00',
    ends_at: '2026-06-23T17:00:00-07:00',
    display_date: 'Jun 20',
    display_time: 'June 20-23',
    location: 'Central Washington University',
    address: null,
    arrival_time: 'Travel details to be confirmed',
    bus_time: null,
    uniform_note: 'Camp gear checklist coming soon',
    equipment_note: null,
    notes: 'Camp dates are June 20-23, 2026. Watch the Weekly Huddle for travel and packing updates.',
    external_url: 'https://www.woodinvillefootball.com/cwucamp',
    is_canceled: false,
    created_by: null,
    created_at: now,
    updated_at: now,
  },
]

export const demoVolunteerSlots: VolunteerSlot[] = [
  {
    id: '60000000-0000-0000-0000-000000000001',
    title: 'Concessions planning',
    description: 'Help prepare concession coverage for early season home events.',
    category: 'game_day',
    team_id: demoTeams[0].id,
    event_id: null,
    starts_at: null,
    ends_at: null,
    display_date: 'June planning',
    display_time: 'Flexible',
    location: 'Remote / stadium',
    slots_needed: 4,
    hour_credit: 2,
    coordinator_profile_id: null,
    created_by: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: '60000000-0000-0000-0000-000000000002',
    title: 'Team meal support',
    description: 'Assist the team parent group with setup and cleanup.',
    category: 'meals',
    team_id: demoTeams[0].id,
    event_id: null,
    starts_at: null,
    ends_at: null,
    display_date: 'Spring football',
    display_time: 'TBD',
    location: 'WHS cafeteria',
    slots_needed: 2,
    hour_credit: 1.5,
    coordinator_profile_id: null,
    created_by: null,
    created_at: now,
    updated_at: now,
  },
]

export const demoVolunteerSlotsWithSummary: VolunteerSlotWithSignupSummary[] = demoVolunteerSlots.map((slot) => ({
  ...slot,
  slots_filled: slot.title === 'Concessions planning' ? 0 : 0,
  signed_up_family_ids: [],
}))

export const demoFamilyProgress: FamilyProgressSummary = {
  action_items_complete: 1,
  action_items_total: 4,
  volunteer_hours_complete: 4,
  volunteer_hours_goal: 10,
}

export const huddleHomeDemo: HuddleHomeModel = {
  huddle: currentHuddle,
  sections: currentHuddleSections,
  urgent_actions: demoActionItems.filter((action) => action.title !== 'Review coach calendar'),
  due_soon_actions: demoActionItems.slice(0, 3),
  upcoming_events: demoEvents,
  volunteer_needs: demoVolunteerSlots,
  family_progress: demoFamilyProgress,
}

export const actionCenterDemo: ActionCenterModel = {
  family: demoFamily,
  items: demoActionItems.map((action) => ({
    action,
    status: demoFamilyActionStatuses.find((status) => status.action_item_id === action.id)!,
  })),
  progress: demoFamilyProgress,
}

export const volunteerCenterDemo: VolunteerCenterModel = {
  slots: demoVolunteerSlotsWithSummary,
  claimed_shifts: [
    {
      id: '61000000-0000-0000-0000-000000000001',
      title: 'Gervais training check-in',
      date_label: 'May 12',
      hours_credited: 2,
    },
    {
      id: '61000000-0000-0000-0000-000000000002',
      title: 'Spring parent meeting setup',
      date_label: 'May 8',
      hours_credited: 2,
    },
  ],
  volunteer_hours_complete: demoFamilyProgress.volunteer_hours_complete,
  volunteer_hours_goal: demoFamilyProgress.volunteer_hours_goal,
}
